In [5]:
import pandas as pd
import numpy as np
from pathlib import Path
import os 
from thefuzz import process
import pandas as pd
import os
import re
import holidays
import tkinter as tk
from tkinter import filedialog
from collections import defaultdict
from clase_reportes_new import ReportClassNew
import json
rc = ReportClassNew()

In [6]:
ruta = rc.validar_ruta()
ruta_shopi =ruta / 'conciliaciones_ecommerce' / 'shopify'
ventas_shopi = rc.consolidar_carpeta(ruta_carpeta=ruta_shopi, extension='csv')
ruta_addi =ruta / 'conciliaciones_ecommerce' / 'addi'
ruta_payu = ruta / 'conciliaciones_ecommerce' / 'payu'

Buscando archivos con extensión '.csv' en: G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\conciliaciones_ecommerce\shopify
  - Archivo 'orders_export_1.csv' leído correctamente.
  - Archivo 'qorders_export_1.csv' leído correctamente.
  - Archivo 'wqqorders_export_1.csv' leído correctamente.
  - Archivo 'orders_export_sws1.csv' leído correctamente.
  - Archivo 'orders_export_2.csv' leído correctamente.
  - Archivo 'orders_export_3.csv' leído correctamente.
  - Archivo 'orders_export_4.csv' leído correctamente.
  - Archivo 'qwdeworders_export_1.csv' leído correctamente.
  - Archivo '22orders_export_2.csv' leído correctamente.
  - Archivo 'aasorders_export_3.csv' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [7]:
ruta_mercado_pago = ruta / 'conciliaciones_ecommerce' / 'mercadopago'

In [8]:
mercado_pago = rc.consolidar_carpeta(ruta_carpeta=ruta_mercado_pago, extension='xlsx')

Buscando archivos con extensión '.xlsx' en: G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\conciliaciones_ecommerce\mercadopago
  - Archivo 'collection-20260303205904-039e.xlsx' leído correctamente.
  - Archivo 'Enero_pcn_POCION.xlsx' leído correctamente.
  - Archivo 'af7e.xlsx' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [9]:
# import pandas as pd
# import zipfile
# from pathlib import Path

# ruta_addi = ruta / 'conciliaciones_ecommerce' / 'addi'

# dfs = []

# for archivo_zip in ruta_addi.glob("*.zip"):
#     if not zipfile.is_zipfile(archivo_zip):
#         df_concatenado = rc.consolidar_carpeta(ruta_carpeta=ruta_addi, extension='csv')
#     print(f"Procesando archivo: {archivo_zip}")
#     with zipfile.ZipFile(archivo_zip, 'r') as z:
#         print(f"Abriendo archivo: {archivo_zip.name}")
#         # Buscar el archivo dentro del zip
#         archivos_internos = [
#             f for f in z.namelist()
#             if 'pagos/' in f.lower() and 'resumen general.xlsx' in f.lower()
#         ]
        
#         print(archivos_internos)
#         if not archivos_internos:
#             print(f"No se encontró el archivo 'resumen general.xlsx' en {archivo_zip.name}")
#             continue
#         print(archivos_internos[0])
#         with z.open(archivos_internos[0]) as archivo_excel:
            
#             df = pd.read_excel(
#                 archivo_excel,
#                 sheet_name='Transacciones + cancelaciones',
#                 engine="calamine"
#             )

#             df = df[~df[df.columns[1]].isna()]
#             df.columns = df.iloc[0].values
#             df = df.iloc[1:]
#             dfs.append(df)

    
# if len(dfs) >1:
#     df_concatenado = pd.concat(dfs, ignore_index=True)
# elif len(dfs)== 1:
#      df_concatenado = dfs[0]         
# df_concatenado = df_concatenado.merge(ventas_shopi[['Payment Reference','Total' ]].dropna(), left_on='Id pedido', right_on='Payment Reference', how='left')
# df_concatenado['Validacion'] = np.where(df_concatenado['Total'] == df_concatenado['Total Después de\ndescuentos (2)'], 'Conciliado', 'No Conciliado')
# # 
# df_concatenado.to_excel(ruta / 'conciliaciones_ecommerce' / 'resultados' / 'addi' / 'conciliado_addi.xlsx', index=False)

In [10]:
ventas_odoo = rc.consolidar_carpeta(ruta_carpeta=r'G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\CLEAN DATA', extension='csv', sep=';')

Buscando archivos con extensión '.csv' en: G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\CLEAN DATA
  - Archivo 'Ventas_Junio_2024_Diciembre_2024.csv' leído correctamente.
  - Archivo 'Ventas_Enero_2025_Diciembre_2025.csv' leído correctamente.
  - Archivo 'Ventas_Enero_2026_Marzo_2026.csv' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [11]:
ventas_odoo.columns

Index(['NUMERO_FACTURA', 'FECHA_FACTURA', 'DIA', 'MES', 'AÑO', 'CLIENTE',
       'IDENTIFICACION_CLIENTE', 'CATEGORÍA', 'PRODUCTO', 'CANTIDAD', 'TOTAL',
       'TRM', 'TOTAL($)', 'TOTAL_CON_IMPUESTOS', 'TELEFONO', 'EMAIL', 'PAIS',
       'CIUDAD_x', 'CIUDAD_CORREGIDA', 'DEPARTAMENTO', 'EQUIPO_VENTAS',
       'REFERENCIA', 'ASESOR COMERCIAL', 'CIUDAD_y', 'ZONA', 'CLIENTE_ORI'],
      dtype='object')

In [19]:
ventas_odoo.columns

Index(['NUMERO_FACTURA', 'FECHA_FACTURA', 'DIA', 'MES', 'AÑO', 'CLIENTE',
       'IDENTIFICACION_CLIENTE', 'CATEGORÍA', 'PRODUCTO', 'CANTIDAD', 'TOTAL',
       'TRM', 'TOTAL($)', 'TOTAL_CON_IMPUESTOS', 'TELEFONO', 'EMAIL', 'PAIS',
       'CIUDAD_x', 'CIUDAD_CORREGIDA', 'DEPARTAMENTO', 'EQUIPO_VENTAS',
       'REFERENCIA', 'ASESOR COMERCIAL', 'CIUDAD_y', 'ZONA', 'CLIENTE_ORI'],
      dtype='object')

In [12]:
ventas_shopi = ventas_shopi.merge(ventas_odoo[['NUMERO_FACTURA','REFERENCIA']], left_on='Name',right_on='REFERENCIA',  how='left')

#odoo shopi

In [24]:
ventas_odoo_sin_pro = pd.read_excel(r'd:\Downloads\ventas.xlsx')

In [31]:
odoo_shopi = ventas_shopi.merge(ventas_odoo_sin_pro[['Número','Referencia','Total firmado']], left_on='Name',right_on='Referencia',  how='left')

In [32]:
odoo_shopi['Validacion'] = np.where(
    odoo_shopi['Total firmado'] == odoo_shopi['Subtotal'],'Conciliado',
        np.where(~odoo_shopi['Financial Status'].isin(['paid']), 'Rechazada/Cancelada',
                    np.where(odoo_shopi['Total firmado'].isna(), 'No esta en shopify',
    'No Conciliado'))
)

In [34]:
odoo_shopi.to_csv(r'd:\Desktop\odoo_shopi.csv', index=False, sep=';', decimal=',')

In [13]:
ventas_shopi['Created at'] = pd.to_datetime(ventas_shopi['Created at'], errors='coerce')

In [14]:
ventas_shopi.sort_values('Created at', inplace=True, ascending=True)

In [15]:
ventas_shopi['Period'] = ventas_shopi['Created at'].dt.to_period('M')

C:\Users\ANALISTA DATOS\AppData\Local\Temp\ipykernel_12980\761140417.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  ventas_shopi['Period'] = ventas_shopi['Created at'].dt.to_period('M')

In [16]:
ventas_shopi['Period'].value_counts()

Period
2025-12    103739
2025-11     53955
2025-06     46732
2025-07     43729
2025-09     42780
2025-10     37910
2025-03     37179
2025-04     35188
2025-05     34826
2026-01     33894
2025-08     33578
2026-02     32939
2025-01     24201
2025-02     22696
Freq: M, Name: count, dtype: int64

In [13]:
# ventas_shopi = ventas_shopi.drop_duplicates(subset='Name',keep='first')

In [14]:
ventas_shopi['Created at'] = ventas_shopi['Created at'].dt.date

In [15]:
# ventas_shopi.to_excel(ruta / 'conciliaciones_ecommerce' / 'resultados' / 'shopi' / 'ventas_shopi.xlsx', index=False)

In [16]:
mercado_pago = mercado_pago.merge(ventas_shopi[['Payment Reference','Total', 'Shipping']].dropna(), left_on='Código de referencia (external_reference)', right_on='Payment Reference', how='left')

In [17]:
import pandas as pd
import numpy as np
import zipfile
from pathlib import Path

ruta = rc.validar_ruta()

ruta_addi = ruta / 'conciliaciones_ecommerce' / 'addi'
ruta_salida = ruta / 'conciliaciones_ecommerce' / 'resultados' / 'addi'
ruta_salida.mkdir(parents=True, exist_ok=True)

dfs = []

# 🔎 Buscar archivos zip
archivos_zip = list(ruta_addi.glob("*.zip"))

if archivos_zip:
    print(f"Se encontraron {len(archivos_zip)} archivos ZIP")

    for archivo_zip in archivos_zip:
        print(f"\nProcesando archivo: {archivo_zip.name}")

        if not zipfile.is_zipfile(archivo_zip):
            print("No es un zip válido, se omite.")
            continue

        with zipfile.ZipFile(archivo_zip, 'r') as z:

            archivos_internos = [
                f for f in z.namelist()
                if 'pagos/' in f.lower() and 'resumen general.xlsx' in f.lower()
            ]

            if not archivos_internos:
                print("No se encontró 'resumen general.xlsx'")
                continue

            with z.open(archivos_internos[0]) as archivo_excel:

                df = pd.read_excel(
                    archivo_excel,
                    sheet_name='Transacciones + cancelaciones',
                    engine="calamine"
                )

                # Limpieza
                df = df[~df[df.columns[1]].isna()]
                df.columns = df.iloc[0].values
                df = df.iloc[1:]

                dfs.append(df)



else:
    print("⚠️ No se encontraron archivos ZIP. Buscando CSV...")
    
    archivos_csv = list(ruta_addi.glob("*.csv"))

    if archivos_csv:
        print(f"Se encontraron {len(archivos_csv)} CSV")
        dfs = rc.consolidar_carpeta(ruta_carpeta=ruta_addi, extension='csv')
    else:
        raise FileNotFoundError("No se encontraron archivos ZIP ni CSV en la carpeta.")

⚠️ No se encontraron archivos ZIP. Buscando CSV...
Se encontraron 14 CSV
Buscando archivos con extensión '.csv' en: G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\conciliaciones_ecommerce\addi
  - Archivo 'transactions ADDI HF ago-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF dic-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF diciembre-2024.csv' leído correctamente.
  - Archivo 'transactions ADDI HF ene-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF feb-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF jul-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF jun-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF mar-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF may-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF nov-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF oct-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF sep-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI HF abr-2025.csv' leído correctamente.
  - Archivo 'transactions ADDI mar-1 a mar 3-2026.csv' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [18]:
ventas_shopi[ventas_shopi['Name']=='#82344']

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,...,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References,NUMERO_FACTURA,REFERENCIA,Period
307650,#82344,martinezjulia353@gmail.com,paid,2025-08-29 22:07:45 -0500,unfulfilled,NaN,yes,COP,103000.0,11000.0,...,NaN,Bogotá,Bogotá,rqTUNjIT6WDyu3nipO98kiiP8,NaN,NaN,rqTUNjIT6WDyu3nipO98kiiP8,NaN,NaN,2025-08
307651,#82344,martinezjulia353@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08
307652,#82344,martinezjulia353@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08

In [19]:
ventas_shopi = ventas_shopi[ventas_shopi['Payment ID'].notna()]

In [27]:

if len(archivos_zip)> 1: 
    df_concatenado = pd.concat(dfs, ignore_index=True)
    ventas_shopi['Payment Reference'] = ventas_shopi['Payment Reference'].str.strip()
    dfs['ID Orden'] = dfs['ID Orden'].str.strip()
    # 🔗 Merge con ventas Shopify
    df_concatenado = df_concatenado.merge(
        ventas_shopi[['Payment Reference', 'Total','Shipping', 'NUMERO_FACTURA']],
        left_on='Id pedido',
        right_on='Payment Reference',
        how='left'
    )
    # ✅ Validación
    df_concatenado['Validacion'] = np.where(
        df_concatenado['Total'] == df_concatenado['Total Después de\ndescuentos (2)'],
        'Conciliado',
        'No Conciliado'
    )
else:  
    ventas_shopi['Payment Reference'] = ventas_shopi['Payment Reference'].str.strip()
    dfs['ID Orden'] = dfs['ID Orden'].str.strip()

    df_concatenado = dfs.merge(
        ventas_shopi[['Payment Reference', 'Total', 'Shipping', 'NUMERO_FACTURA']],
        left_on='ID Orden',
        right_on='Payment Reference',
        how='left'
    )

    # ✅ Validación
    df_concatenado['Validacion'] = np.where(
        df_concatenado['Total'] == df_concatenado['Monto'],'Conciliado',
            np.where(df_concatenado['Estado'].isin(['Cancelada', 'Abandono','Rechazada']), 'Rechazada/Cancelada',
                     np.where(df_concatenado['Total'].isna(), 'No esta en shopify',
        'No Conciliado'))
    )

In [29]:


# 💾 Guardar resultado
df_concatenado.to_excel(
    ruta_salida / 'conciliado_addi.xlsx',
    index=False
)

print("✅ Archivo generado correctamente")

✅ Archivo generado correctamente

In [ ]:
mercado_pago['Validacion'] = np.where(
    mercado_pago['Total'] == mercado_pago['Valor del producto (transaction_amount)'],'Conciliado',
        np.where(~mercado_pago['Estado de la operación (status)'].isin(['approved']), 'Rechazada/Cancelada',
                    np.where(mercado_pago['Total'].isna(), 'No esta en shopify',
    'No Conciliado'))
)
mercado_pago.to_excel(ruta / 'conciliaciones_ecommerce' / 'resultados' / 'mercadopago' / 'conciliado_mercadopago.xlsx', index=False)

In [51]:
ventas_shopi[ventas_shopi['Name']=='#82344']

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,...,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References
89761,#82344,martinezjulia353@gmail.com,paid,2025-08-29 22:07:45 -0500,unfulfilled,NaN,yes,COP,103000.0,11000.0,...,NaN,NaN,NaN,NaN,Bogotá,Bogotá,rqTUNjIT6WDyu3nipO98kiiP8,NaN,NaN,rqTUNjIT6WDyu3nipO98kiiP8
89762,#82344,martinezjulia353@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89763,#82344,martinezjulia353@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# PAYU

In [ ]:
mercado_pago = mercado_pago.merge(ventas_shopi[['Payment Reference','Total', 'Shipping']].dropna(), left_on='Código de referencia (external_reference)', right_on='Payment Reference', how='left')

In [39]:
payu = rc.consolidar_carpeta(ruta_carpeta=ruta_payu, extension='csv')

Buscando archivos con extensión '.csv' en: G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\conciliaciones_ecommerce\payu
  - Archivo '07.Julio.csv' leído correctamente.
  - Archivo '08.Agosto.csv' leído correctamente.
  - Archivo '09.Septiembre.csv' leído correctamente.
  - Archivo '10.Octubre.csv' leído correctamente.
  - Archivo '01.Enero.csv' leído correctamente.
  - Archivo '02.Febrero.csv' leído correctamente.
  - Archivo '03.Marzo.csv' leído correctamente.
  - Archivo '04.Abril.csv' leído correctamente.
  - Archivo '05.Mayo.csv' leído correctamente.
  - Archivo '06.Junio.csv' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [42]:
payu.columns

Index(['Id Transacción', 'Id Orden', 'Fecha de creación',
       'Última actualización', 'Referencia', 'Descripción',
       'Nombre del pagador', 'Email del comprador', 'Valor original',
       'Moneda original', 'Valor procesado', 'Moneda procesada',
       'Estado de orden', 'Medio de pago', 'Tipo de tarjeta de crédito',
       'Número visible tarjeta de crédito', 'Banco emisor',
       'Tipo de transacción', 'Estado de transacción', 'Código de respuesta',
       'Número de cuotas totales', 'Código de trazabilidad', 'id aliado',
       'Fecha aprobación pago'],
      dtype='object')

In [45]:
payu = payu.merge(ventas_shopi[['Payment Reference','Total', 'Shipping']].dropna(), left_on='Referencia',right_on='Payment Reference', how='left')

In [50]:
payu['Código de respuesta'].value_counts()

Código de respuesta
APPROVED                                    20821
ANTIFRAUD_REJECTED                           1228
ABANDONED_TRANSACTION                        1194
PAYMENT_NETWORK_REJECTED                      979
ENTITY_DECLINED                               878
INVALID_TRANSACTION                           616
INSUFFICIENT_FUNDS                            334
NOT_ACCEPTED_TRANSACTION                      322
RESTRICTED_CARD                               190
INVALID_EXPIRATION_DATE_OR_SECURITY_CODE      171
INVALID_CARD                                  139
BANK_UNREACHABLE                              135
EXCEEDED_AMOUNT                               132
BANK_FRAUD_REJECTED                            84
INVALID_BANK_ACCOUNT                           56
PENDING_TRANSACTION_CONFIRMATION               50
PENDING_PAYMENT_IN_ENTITY                      44
PENDING_TRANSACTION_REVIEW                     34
EXPIRED_CARD                                   30
INTERNAL_PAYMENT_PROVIDER_ERROR                26
REPEAT_TRANSACTION                             12
ERROR                                           9
INACTIVE_PAYMENT_PROVIDER                       5
Name: count, dtype: int64

In [47]:
payu['Validacion'] = np.where(
    payu['Total'] == payu['Valor procesado'],'Conciliado',
        np.where(~payu['Estado de transacción'].isin(['approved']), 'Rechazada/Cancelada',
                    np.where(payu['Total'].isna(), 'No esta en shopify',
    'No Conciliado'))
)

In [48]:

payu.to_excel(ruta / 'conciliaciones_ecommerce' / 'resultados' / 'payu' / 'conciliado_payu.xlsx', index=False)