In [8]:
import pandas as pd
from pathlib import Path
import os 
from thefuzz import process
import pandas as pd
import os
import re
import tkinter as tk
from tkinter import filedialog
from clase_reportes import ReportClass
rc = ReportClass()

In [28]:
import os 
import pandas as pd

carpeta_seleccionada = r'C:\Users\Dataa\Desktop\VENTAS\VENTA MENSUAL\data\nielseiq'

lista_dataframes = []


for archivo in os.listdir(carpeta_seleccionada):
    if archivo.endswith(f'.{'xlsx'}'):
        ruta_completa = os.path.join(carpeta_seleccionada, archivo)
        try:
            
            df_o_dict = pd.read_excel(ruta_completa)
            new_header = df_o_dict.iloc[7]

            # Paso 2: Crear nuevo DataFrame desde la fila 8 en adelante, usando ese header
            df_o_dict_limpio = df_o_dict[8:].copy()
            df_o_dict_limpio.columns = new_header
            df_o_dict_limpio.reset_index(drop=True, inplace=True)
            df_o_dict_limpio = df_o_dict_limpio[df_o_dict_limpio['Periods'].notna()].reset_index(drop=True)
            df_o_dict_limpio = df_o_dict_limpio.convert_dtypes()

            lista_dataframes.append(df_o_dict_limpio)   

        except Exception as e:
            print(f"  - No se pudo leer el archivo '{archivo}'. Error: {e}")

print("Concatenando todos los archivos...")
df_concatenado = pd.concat(lista_dataframes, ignore_index=True)
print("¡Consolidación completada!")

Concatenando todos los archivos...
¡Consolidación completada!

In [29]:
lista_dataframes[2].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50114 entries, 0 to 50113
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Markets                       50114 non-null  string
 1   Periods                       50114 non-null  string
 2   CATEGORIA                     50114 non-null  string
 3   FABRICANTES                   50114 non-null  string
 4   MARCAS                        50114 non-null  string
 5   ITEM                          50114 non-null  string
 6   PRESENTACION UNIF.            50114 non-null  string
 7   TIPO UNIF.                    50114 non-null  string
 8   PROMOCION/NO PROMOCION UNIF.  50114 non-null  string
 9   PESO VOL. UNITARIO UNIF.      50114 non-null  string
 10  Vtas Valor                    50114 non-null  Float64
 11  Vtas Unds                     50114 non-null  Float64
 12  Dist. Num.                    50114 non-null  Float64
dtypes: Float64(3), string(10)
memory usage: 5.1 MB

In [19]:
df_o_dict_limpio[df_o_dict_limpio['Periods'].notna()]

7,Markets,Periods,CATEGORIA,FABRICANTES,MARCAS,ITEM,PRESENTACION UNIF.,TIPO UNIF.,PROMOCION/NO PROMOCION UNIF.,PESO VOL. UNITARIO UNIF.,Vtas Valor,Vtas Unds,Dist. Num.
0,TOTAL COLOMBIA FARMACIAS,YTD 1 S 08/01/23,TRATAMIENTOS CAPILARES,A.C. MARCA,PILOPEPTAN,PILOPEPTAN LOCION BOTELLA 100ML IMP,LOCION,OTROS TIPOS,NO PROMOCION,100,518800,4,0.105513
1,TOTAL COLOMBIA FARMACIAS,YTD 1 S 08/01/23,TRATAMIENTOS CAPILARES,BELLEZA EXPRESS,BIOHERBAL,BIOHERBAL LOC CAP ANTIC BT 120ML + SHA REG ANT...,LOCION,OTROS TIPOS,PROMOCION,120,80886,4,0.105513
2,TOTAL COLOMBIA FARMACIAS,YTD 1 S 08/01/23,TRATAMIENTOS CAPILARES,BELLEZA EXPRESS,BIOHERBAL,BIOHERBAL LOCION CAPILAR ANTICAIDA BOTELLA 120ML,LOCION,OTROS TIPOS,NO PROMOCION,120,192664,8,0.211026
3,TOTAL COLOMBIA FARMACIAS,YTD 1 S 08/01/23,TRATAMIENTOS CAPILARES,BELLEZA EXPRESS,BIOHERBAL,BIOHERBAL REPARACION INFUSIONES BOTANICAS CREM...,CREMA,OTROS TIPOS,NO PROMOCION,250,159444,9,0.211026
4,TOTAL COLOMBIA FARMACIAS,YTD 1 S 08/01/23,TRATAMIENTOS CAPILARES,BELLEZA EXPRESS,BIOHERBAL,BIOHERBAL REPARACION TB 250ML + SHA REG BT 400ML],OTRAS PRESENTACIONES,OTROS TIPOS,NO PROMOCION,250,36720.0408,2,0.052757
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50109,TOTAL COLOMBIA FARMACIAS,YTD 34 S 24/08/25,TRATAMIENTOS CAPILARES,UNILEVER,SEDAL,SEDAL RIZOS DEFINIDOS MASCARILLA POTE 300GR,MASCARILLA,OTROS TIPOS,NO PROMOCION,300,143200,8,0.005421
50110,TOTAL COLOMBIA FARMACIAS,YTD 34 S 24/08/25,TRATAMIENTOS CAPILARES,WELLA,WELLA,WELLA INVIGO BRILLANCE MASCARILLA LIME CAVIAR ...,MASCARILLA,OTROS TIPOS,NO PROMOCION,150,322500,3,0.002032
50111,TOTAL COLOMBIA FARMACIAS,YTD 34 S 24/08/25,TRATAMIENTOS CAPILARES,WELLA,WELLA,WELLA INVIGO MASCARILLA NUTRI ENRICH POTE 150ML,MASCARILLA,OTROS TIPOS,NO PROMOCION,150,150500,3,0.002032
50112,TOTAL COLOMBIA FARMACIAS,YTD 34 S 24/08/25,TRATAMIENTOS CAPILARES,WONDER GOLD,HAIRFIT,HAIRFIT ACEITE ARGAN BOTELLA 30ML,OTRAS PRESENTACIONES,OTROS TIPOS,NO PROMOCION,30,14970,1,0.000677
50113,TOTAL COLOMBIA FARMACIAS,YTD 34 S 24/08/25,TRATAMIENTOS CAPILARES,WONDER GOLD,HAIRFIT,HAIRFIT MASCARILLA REPOLARIZADORA POTE 300GR,MASCARILLA,OTROS TIPOS,NO PROMOCION,300,768940,52,0.015585

In [11]:
df_concatenado = pd.concat(lista_dataframes, ignore_index=True)

In [12]:
df_concatenado['Markets'].value_counts()

Markets
TOTAL COLOMBIA FARMACIAS                                                                                                                                                       226881
Exportado: 6 oct 2025                                                                                                                                                               3
Dataset: NielsenIQ Retail Measurement | CO - NIQ CENTRALIZED STANDARD MANUF - ST   | CO - LA POCION - INDUSTRY SHAMPO_BALSAMOS_TRATAMIENTO - ST  | Currency: Colombian peso         3
Copyright © 2025 Nielsen Consumer LLC. Todos los derechos reservados.                                                                                                               3
Terms & Conditions                                                                                                                                                                  3
Name: count, dtype: int64

In [6]:
lista_dataframes[2]

7,Markets,Periods,CATEGORIA,FABRICANTES,MARCAS,ITEM,PRESENTACION UNIF.,TIPO UNIF.,PROMOCION/NO PROMOCION UNIF.,PESO VOL. UNITARIO UNIF.,Vtas Valor,Vtas Unds,Dist. Num.
0,TOTAL COLOMBIA FARMACIAS,YTD 1 S 08/01/23,TRATAMIENTOS CAPILARES,A.C. MARCA,PILOPEPTAN,PILOPEPTAN LOCION BOTELLA 100ML IMP,LOCION,OTROS TIPOS,NO PROMOCION,100,518800,4,0.105513
1,TOTAL COLOMBIA FARMACIAS,YTD 1 S 08/01/23,TRATAMIENTOS CAPILARES,BELLEZA EXPRESS,BIOHERBAL,BIOHERBAL LOC CAP ANTIC BT 120ML + SHA REG ANT...,LOCION,OTROS TIPOS,PROMOCION,120,80886,4,0.105513
2,TOTAL COLOMBIA FARMACIAS,YTD 1 S 08/01/23,TRATAMIENTOS CAPILARES,BELLEZA EXPRESS,BIOHERBAL,BIOHERBAL LOCION CAPILAR ANTICAIDA BOTELLA 120ML,LOCION,OTROS TIPOS,NO PROMOCION,120,192664,8,0.211026
3,TOTAL COLOMBIA FARMACIAS,YTD 1 S 08/01/23,TRATAMIENTOS CAPILARES,BELLEZA EXPRESS,BIOHERBAL,BIOHERBAL REPARACION INFUSIONES BOTANICAS CREM...,CREMA,OTROS TIPOS,NO PROMOCION,250,159444,9,0.211026
4,TOTAL COLOMBIA FARMACIAS,YTD 1 S 08/01/23,TRATAMIENTOS CAPILARES,BELLEZA EXPRESS,BIOHERBAL,BIOHERBAL REPARACION TB 250ML + SHA REG BT 400ML],OTRAS PRESENTACIONES,OTROS TIPOS,NO PROMOCION,250,36720.0408,2,0.052757
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50116,Exportado: 6 oct 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50117,Dataset: NielsenIQ Retail Measurement | CO - N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50118,Copyright © 2025 Nielsen Consumer LLC. Todos l...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50119,Terms & Conditions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:

print("Concatenando todos los archivos...")
df_concatenado = pd.concat(lista_dataframes, ignore_index=True)
print("¡Consolidación completada!")

In [ ]:

print("Concatenando todos los archivos...")
df_concatenado = pd.concat(lista_dataframes, ignore_index=True)
print("¡Consolidación completada!")

return df_concatenado

In [ ]:
# # Filtrar ventas por año

# ventas = pd.read_excel(r"C:\Users\Dataa\Downloads\ventas.xlsx")
   
# ventas = ventas[ventas['Líneas de factura/Número'].notna()]
# ventas['Líneas de factura/Fecha de factura'] = pd.to_datetime(ventas['Líneas de factura/Fecha de factura'])
# ventas =  ventas[ventas['Líneas de factura/Fecha de factura'].dt.year == 2025]


# notas = pd.read_excel(r"C:\Users\Dataa\Downloads\ventas.xlsx")


   
# notas = notas[notas['Líneas de factura/Número'].notna()]
# notas['Líneas de factura/Fecha de factura'] = pd.to_datetime(notas['Líneas de factura/Fecha de factura'])
# notas =  notas[notas['Líneas de factura/Fecha de factura'].dt.year == 2025]

In [ ]:
# # correo angelica
# ventas = pd.read_excel(r"C:\Users\Dataa\Desktop\VENTAS\VENTA MENSUAL\file\BASE VENTAS 2025.xlsx")
# ventas.columns
# ventas['CATEGORÍA'].value_counts()
# ventas_filtro = ventas[(ventas['PRODUCTO'].isin(['[TNGL05] EMULGEL RIZOS TONGOLÉ', '[PCNKIT20] KIT DEFINICIÓN TOTAL TONGOLÉ']))&
#                        (ventas['CATEGORÍA'].isin(['SHOPIFY', 'CALL CENTER']))].reset_index()
# import numpy as np
# ventas_filtro['ORIGEN'] = np.where(
#     ventas_filtro['PRODUCTO'] == '[TNGL05] EMULGEL RIZOS TONGOLÉ',
#     'INDIVIDUAL',
#     'KIT'
# )
# ventas_filtro['PRODUCTO_F'] = '[TNGL05] EMULGEL RIZOS TONGOLÉ'
# ventas_filtro = ventas_filtro[ventas_filtro['CIUDAD']=='Cali']
# ventas_filtro.columns
# ventas_filtro.groupby(['CLIENTE', 'ORIGEN']).agg(
#     PRODUCTO=('PRODUCTO_F', 'first'),
#     TOTAL_COMPRAS=('NUMERO_FACTURA', 'count'),
#     PRIMERA_COMPRA=('FECHA_FACTURA', 'min'),
#     ULTIMA_COMPRA=('FECHA_FACTURA', 'max'),
#     TELEFONO=('TELEFONO', 'first'),
#     TOTAL_CANTIDAD=('CANTIDAD', 'sum')
# ).reset_index().to_excel(r"C:\Users\Dataa\Desktop\base_gel_tongole.xlsx")