In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path
import os 
from thefuzz import process
import pandas as pd
import os
import re
import holidays
import tkinter as tk
from tkinter import filedialog
from collections import defaultdict
from classes.clase_reportes_new import ReportClassNew
import json
rc = ReportClassNew()

In [2]:
shopi = pd.read_csv(r'D:\Downloads\orders_export_1.csv')

C:\Users\ANALISTA DATOS\AppData\Local\Temp\ipykernel_33116\686841851.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  shopi = pd.read_csv(r'D:\Downloads\orders_export_1.csv')

In [4]:
apuntes = pd.read_excel(r'D:\Downloads\Apunte Contable 2025 mercadopago.xlsx')

In [7]:
mercadopago = pd.read_excel(r'D:\Downloads\Mvtos mercadopago de ago a dic 2025.xlsx')

In [15]:
mercadopago.shape

(15615, 57)

In [20]:
shopi.to_excel(r'D:\Downloads\shopi.xlsx', index=False)

In [14]:
mercadopago.merge(shopi, right_on='Payment Reference', left_on='NÚMERO DE IDENTIFICACIÓN', how='left').shape

(130261, 136)

In [18]:
shopi = rc.consolidar_carpeta(ruta_carpeta=r'D:\Desktop\shopi', extension='csv')

Buscando archivos con extensión '.csv' en: D:\Desktop\shopi
  - Archivo 'orders_export_1.csv' leído correctamente.
  - Archivo 'orders_export_2.csv' leído correctamente.
  - Archivo 'orders_export_3.csv' leído correctamente.
  - Archivo 'orders_export_4.csv' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [12]:
shopi.merge(mercadopago, right_on='NÚMERO DE IDENTIFICACIÓN', left_on='Payment Reference', how='left').shape

(119544, 136)

In [8]:
mercadopago.columns

Index(['NÚMERO DE IDENTIFICACIÓN', 'ID DE OPERACIÓN EN MERCADO PAGO',
       'CÓDIGO DE LA CUENTA DEL VENDEDOR', 'TIPO DE MEDIO DE PAGO',
       'MEDIO DE PAGO', 'PAÍS DE ORIGEN DE LA CUENTA DE MERCADO PAGO',
       'TIPO DE OPERACIÓN', 'VALOR DE LA COMPRA', 'MONEDA',
       'MONTO RECIBIDO POR COMPRAS POR SPLIT', 'FECHA DE ORIGEN',
       'COMISIONES + IVA', 'MONTO NETO DE LA OPERACIÓN QUE IMPACTÓ TU DINERO',
       'MONEDA DE LA LIQUIDACIÓN', 'FECHA DE APROBACIÓN',
       'MONTO NETO DE LA OPERACIÓN', 'CUPÓN DE DESCUENTO', 'DATOS EXTRA',
       'COMISIÓN DE MERCADO LIBRE + IVA',
       'COMISIÓN POR OFRECER CUOTAS SIN INTERÉS', 'COSTO DE ENVÍO',
       'IMPUESTOS COBRADOS POR RETENCIONES DE IIBB', 'CUOTAS',
       'DETALLE DE IMPUESTOS', 'ID DE CAJA', 'ID DE TIENDA',
       'NOMBRE DE TIENDA', 'ID DE CAJA DEFINIDO POR EL USUARIO',
       'NOMBRE DE CAJA', 'ID DE TIENDA DEFINIDO POR EL USUARIO',
       'ID DE LA ORDEN', 'ID DEL ENVÍO', 'MODO DE ENVÍO', 'ID DEL PAQUETE',
       'IMPUESTOS DESAGREGADOS', 'NÚMERO DE SERIE DEL LECTOR (S/N)',
       'BILLETERA VIRTUAL', 'BANCO DE ORIGEN', 'NÚMERO INICIAL DE TARJETA',
       'OPERATION_TAGS', 'CANAL DE VENTA', 'PLATAFORMA DE COBRO',
       'FECHA DE LIBERACIÓN DEL DINERO', 'CÓDIGO DE PRODUCTO SKU',
       'DETALLE DE LA VENTA', 'ID DE INTENTO DE OPERACIÓN', 'FRANCHISE',
       'LAST_FOUR_DIGITS', 'ID DE LA SOLICITUD', 'PERIODO DE FACTURACIÓN',
       'NOMBRE DEL EMISOR', 'NÚMERO DE CUENTA BANCARIA DE PAGO', 'LIBERADO',
       'MONTO DE LA PROPINA', 'ID DE LA COMPRA', 'ID DE ASOCIACIÓN DE ENVÍOS',
       'MONTO TOTAL DEL CUPÓN DE DESCUENTO'],
      dtype='object')

In [6]:

shopi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13073 entries, 0 to 13072
Data columns (total 79 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name                         13073 non-null  object
 1   Email                        13073 non-null  object
 2   Financial Status             4939 non-null   object
 3   Paid at                      4883 non-null   object
 4   Fulfillment Status           4939 non-null   object
 5   Fulfilled at                 1 non-null      object
 6   Accepts Marketing            4939 non-null   object
 7   Currency                     4939 non-null   object
 8   Subtotal                     4939 non-null   float64
 9   Shipping                     4939 non-null   float64
 10  Taxes                        4939 non-null   float64
 11  Total                        4939 non-null   float64
 12  Discount Code                1369 non-null   object
 13  Discount Amount              4939 non-null   float64
 14  Shipping Method              4939 non-null   object
 15  Created at                   13073 non-null  object
 16  Lineitem quantity            13073 non-null  int64
 17  Lineitem name                13073 non-null  object
 18  Lineitem price               13073 non-null  float64
 19  Lineitem compare at price    235 non-null    float64
 20  Lineitem sku                 13073 non-null  object
 21  Lineitem requires shipping   13073 non-null  bool
 22  Lineitem taxable             13073 non-null  bool
 23  Lineitem fulfillment status  13073 non-null  object
 24  Billing Name                 4939 non-null   object
 25  Billing Street               4939 non-null   object
 26  Billing Address1             4939 non-null   object
 27  Billing Address2             4398 non-null   object
 28  Billing Company              4875 non-null   object
 29  Billing City                 4939 non-null   object
 30  Billing Zip                  2340 non-null   object
 31  Billing Province             4939 non-null   object
 32  Billing Country              4939 non-null   object
 33  Billing Phone                4929 non-null   float64
 34  Shipping Name                4939 non-null   object
 35  Shipping Street              4939 non-null   object
 36  Shipping Address1            4939 non-null   object
 37  Shipping Address2            4413 non-null   object
 38  Shipping Company             4927 non-null   object
 39  Shipping City                4939 non-null   object
 40  Shipping Zip                 2337 non-null   object
 41  Shipping Province            4939 non-null   object
 42  Shipping Country             4939 non-null   object
 43  Shipping Phone               4939 non-null   float64
 44  Notes                        475 non-null    object
 45  Note Attributes              3151 non-null   object
 46  Cancelled at                 0 non-null      float64
 47  Payment Method               4934 non-null   object
 48  Payment Reference            4883 non-null   object
 49  Refunded Amount              4939 non-null   float64
 50  Vendor                       13073 non-null  object
 51  Outstanding Balance          4939 non-null   float64
 52  Employee                     0 non-null      float64
 53  Location                     0 non-null      float64
 54  Device ID                    0 non-null      float64
 55  Id                           4939 non-null   float64
 56  Tags                         4938 non-null   object
 57  Risk Level                   4939 non-null   object
 58  Source                       4939 non-null   object
 59  Lineitem discount            13073 non-null  float64
 60  Tax 1 Name                   4939 non-null   object
 61  Tax 1 Value                  4939 non-null   float64
 62  Tax 2 Name                   0 non-null      float64
 63  Tax 2 Value                  0 non-null      float64
 64  Tax 3 Name                   0 non-null      float64
 65  Tax 3 Value                  0 non-null      float64
 66  Tax 4 Name                   0 non-null      float64
 67  Tax 4 Value                  0 non-null      float64
 68  Tax 5 Name                   0 non-null      float64
 69  Tax 5 Value                  0 non-null      float64
 70  Phone                        0 non-null      float64
 71  Receipt Number               0 non-null      float64
 72  Duties                       0 non-null      float64
 73  Billing Province Name        4939 non-null   object
 74  Shipping Province Name       4939 non-null   object
 75  Payment ID                   4883 non-null   object
 76  Payment Terms Name           0 non-null      float64
 77  Next Payment Due At          0 non-null      float64
 78  Payment References           4934 non-null   object
dtypes: bool(2), float64(31), int64(1), object(45)
memory usage: 7.7+ MB

In [2]:
# Validar ruta y consolidar datos de Shopify
ruta = rc.validar_ruta()
ruta_shopi =ruta / 'conciliaciones_ecommerce' / 'shopify'
ventas_shopi = rc.consolidar_carpeta(ruta_carpeta=ruta_shopi, extension='csv')
ruta_addi =ruta / 'conciliaciones_ecommerce' / 'addi'
ruta_payu = ruta / 'conciliaciones_ecommerce' / 'payu'

Buscando archivos con extensión '.csv' en: G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\conciliaciones_ecommerce\shopify
  - Archivo 'orders_export_1.csv' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [3]:
ventas_shopi.to_excel(r'G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\conciliaciones_ecommerce\resultados\shopi\ventas_shopi2.xlsx')

In [4]:
ruta_mercado_pago = ruta / 'conciliaciones_ecommerce' / 'mercadopago'
mercado_pago = rc.consolidar_carpeta(ruta_carpeta=ruta_mercado_pago, extension='xlsx')

Buscando archivos con extensión '.xlsx' en: G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\conciliaciones_ecommerce\mercadopago

d:\Desktop\analisis_datos\virtual-env\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  - Archivo 'settlement_v2-2582716442-manual-2026-04-28-110747 (1).xlsx' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [5]:
# import pandas as pd
# import zipfile
# from pathlib import Path

# ruta_addi = ruta / 'conciliaciones_ecommerce' / 'addi'

# dfs = []

# for archivo_zip in ruta_addi.glob("*.zip"):
#     if not zipfile.is_zipfile(archivo_zip):
#         df_concatenado = rc.consolidar_carpeta(ruta_carpeta=ruta_addi, extension='csv')
#     print(f"Procesando archivo: {archivo_zip}")
#     with zipfile.ZipFile(archivo_zip, 'r') as z:
#         print(f"Abriendo archivo: {archivo_zip.name}")
#         # Buscar el archivo dentro del zip
#         archivos_internos = [
#             f for f in z.namelist()
#             if 'pagos/' in f.lower() and 'resumen general.xlsx' in f.lower()
#         ]
        
#         print(archivos_internos)
#         if not archivos_internos:
#             print(f"No se encontró el archivo 'resumen general.xlsx' en {archivo_zip.name}")
#             continue
#         print(archivos_internos[0])
#         with z.open(archivos_internos[0]) as archivo_excel:
            
#             df = pd.read_excel(
#                 archivo_excel,
#                 sheet_name='Transacciones + cancelaciones',
#                 engine="calamine"
#             )

#             df = df[~df[df.columns[1]].isna()]
#             df.columns = df.iloc[0].values
#             df = df.iloc[1:]
#             dfs.append(df)

    
# if len(dfs) >1:
#     df_concatenado = pd.concat(dfs, ignore_index=True)
# elif len(dfs)== 1:
#      df_concatenado = dfs[0]         
# df_concatenado = df_concatenado.merge(ventas_shopi[['Payment Reference','Total' ]].dropna(), left_on='Id pedido', right_on='Payment Reference', how='left')
# df_concatenado['Validacion'] = np.where(df_concatenado['Total'] == df_concatenado['Total Después de\ndescuentos (2)'], 'Conciliado', 'No Conciliado')
# # 
# df_concatenado.to_excel(ruta / 'conciliaciones_ecommerce' / 'resultados' / 'addi' / 'conciliado_addi.xlsx', index=False)

In [5]:
ventas_odoo = rc.consolidar_carpeta(ruta_carpeta=r'G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\CLEAN DATA', extension='csv', sep=';')

Buscando archivos con extensión '.csv' en: G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\CLEAN DATA
  - Archivo 'Ventas_Junio_2024_Diciembre_2024.csv' leído correctamente.
  - Archivo 'Ventas_Enero_2025_Diciembre_2025.csv' leído correctamente.
  - Archivo 'Ventas_Enero_2026_Marzo_2026.csv' leído correctamente.
  - Archivo 'Ventas_Abril_2026.csv' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [6]:
ventas_shopi = ventas_shopi.merge(ventas_odoo[['NUMERO_FACTURA','REFERENCIA']], left_on='Name',right_on='REFERENCIA',  how='left')

#odoo shopi

In [7]:
ventas_shopi.to_excel(r'D:\desktop\ventas_shopi.xlsx', index=False)

In [7]:
ventas_odoo_sin_pro = pd.read_excel(r'd:\Downloads\Asiento contable (account.move) (76).xlsx')

In [8]:
ventas_odoo.columns

Index(['NUMERO_FACTURA', 'FECHA_FACTURA', 'DIA', 'MES', 'AÑO', 'CLIENTE',
       'IDENTIFICACION_CLIENTE', 'CATEGORÍA', 'PRODUCTO', 'CANTIDAD', 'TOTAL',
       'TRM', 'TOTAL($)', 'TOTAL_CON_IMPUESTOS', 'TELEFONO', 'EMAIL', 'PAIS',
       'CIUDAD_x', 'CIUDAD_CORREGIDA', 'DEPARTAMENTO', 'EQUIPO_VENTAS',
       'REFERENCIA', 'ASESOR COMERCIAL', 'CIUDAD_y', 'ZONA', 'CLIENTE_ORI'],
      dtype='object')

In [9]:
odoo_shopi = ventas_shopi.merge(ventas_odoo_sin_pro[['Número','Referencia','Total firmado']], left_on='Name',right_on='Referencia',  how='left')

In [10]:
odoo_shopi['Validacion'] = np.where(
    odoo_shopi['Total firmado'] == odoo_shopi['Subtotal'],'Conciliado',
        np.where(~odoo_shopi['Financial Status'].isin(['paid']), 'Rechazada/Cancelada',
                    np.where(odoo_shopi['Total firmado'].isna(), 'No esta en Odoo',
    'No Conciliado'))
)

In [11]:
odoo_shopi.to_csv(r'd:\Desktop\odoo_shopi.csv', index=False, sep=';', decimal=',')

In [12]:
ventas_shopi['Created at'] = pd.to_datetime(ventas_shopi['Created at'], errors='coerce')

In [13]:
ventas_shopi.sort_values('Created at', inplace=True, ascending=True)

In [14]:
ventas_shopi['Period'] = ventas_shopi['Created at'].dt.to_period('M')

C:\Users\ANALISTA DATOS\AppData\Local\Temp\ipykernel_6968\761140417.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  ventas_shopi['Period'] = ventas_shopi['Created at'].dt.to_period('M')

In [15]:
ventas_shopi['Period'].value_counts()

Period
2026-03    39242
2026-02    31924
2026-01     7105
Freq: M, Name: count, dtype: int64

In [16]:
# ventas_shopi = ventas_shopi.drop_duplicates(subset='Name',keep='first')

In [17]:
ventas_shopi['Created at'] = ventas_shopi['Created at'].dt.date

In [18]:
# ventas_shopi.to_excel(ruta / 'conciliaciones_ecommerce' / 'resultados' / 'shopi' / 'ventas_shopi.xlsx', index=False)

In [22]:
mercado_pago.columns

Index(['NÚMERO DE IDENTIFICACIÓN', 'ID DE OPERACIÓN EN MERCADO PAGO',
       'CÓDIGO DE LA CUENTA DEL VENDEDOR', 'TIPO DE MEDIO DE PAGO',
       'MEDIO DE PAGO', 'PAÍS DE ORIGEN DE LA CUENTA DE MERCADO PAGO',
       'TIPO DE OPERACIÓN', 'VALOR DE LA COMPRA', 'MONEDA',
       'MONTO RECIBIDO POR COMPRAS POR SPLIT', 'FECHA DE ORIGEN',
       'COMISIONES + IVA', 'MONTO NETO DE LA OPERACIÓN QUE IMPACTÓ TU DINERO',
       'MONEDA DE LA LIQUIDACIÓN', 'FECHA DE APROBACIÓN',
       'MONTO NETO DE LA OPERACIÓN', 'CUPÓN DE DESCUENTO', 'DATOS EXTRA',
       'COMISIÓN DE MERCADO LIBRE + IVA',
       'COMISIÓN POR OFRECER CUOTAS SIN INTERÉS', 'COSTO DE ENVÍO',
       'IMPUESTOS COBRADOS POR RETENCIONES DE IIBB', 'CUOTAS',
       'DETALLE DE IMPUESTOS', 'ID DE CAJA', 'ID DE TIENDA',
       'NOMBRE DE TIENDA', 'ID DE CAJA DEFINIDO POR EL USUARIO',
       'NOMBRE DE CAJA', 'ID DE TIENDA DEFINIDO POR EL USUARIO',
       'ID DE LA ORDEN', 'ID DEL ENVÍO', 'MODO DE ENVÍO', 'ID DEL PAQUETE',
       'IMPUESTOS DESAGREGADOS', 'NÚMERO DE SERIE DEL LECTOR (S/N)',
       'BILLETERA VIRTUAL', 'BANCO DE ORIGEN', 'NÚMERO INICIAL DE TARJETA',
       'OPERATION_TAGS', 'CANAL DE VENTA', 'PLATAFORMA DE COBRO',
       'FECHA DE LIBERACIÓN DEL DINERO', 'CÓDIGO DE PRODUCTO SKU',
       'DETALLE DE LA VENTA', 'ID DE INTENTO DE OPERACIÓN', 'FRANCHISE',
       'LAST_FOUR_DIGITS', 'ID DE LA SOLICITUD', 'PERIODO DE FACTURACIÓN',
       'NOMBRE DEL EMISOR', 'NÚMERO DE CUENTA BANCARIA DE PAGO', 'LIBERADO',
       'MONTO DE LA PROPINA', 'ID DE LA COMPRA', 'ID DE ASOCIACIÓN DE ENVÍOS',
       'MONTO TOTAL DEL CUPÓN DE DESCUENTO'],
      dtype='object')

In [ ]:
df_mercado = None
if 'Código de referencia (external_reference)' in mercado_pago.columns:
    mercado_pago = mercado_pago.rename(columns={'Código de referencia (external_reference)': 'external_reference'})
else: 
    mercado_pago = mercado_pago.rename(columns={'NÚMERO DE IDENTIFICACIÓN': 'external_reference'})
    df_mercado = True

In [24]:
mercado_pago = mercado_pago.merge(ventas_shopi[['Payment Reference','Total', 'Shipping']].dropna(), left_on='external_reference', right_on='Payment Reference', how='left')

In [25]:
import pandas as pd
import numpy as np
import zipfile
from pathlib import Path

ruta = rc.validar_ruta()

ruta_addi = ruta / 'conciliaciones_ecommerce' / 'addi'
ruta_salida = ruta / 'conciliaciones_ecommerce' / 'resultados' / 'addi'
ruta_salida.mkdir(parents=True, exist_ok=True)

dfs = []

# 🔎 Buscar archivos zip
archivos_zip = list(ruta_addi.glob("*.zip"))

if archivos_zip:
    print(f"Se encontraron {len(archivos_zip)} archivos ZIP")

    for archivo_zip in archivos_zip:
        print(f"\nProcesando archivo: {archivo_zip.name}")

        if not zipfile.is_zipfile(archivo_zip):
            print("No es un zip válido, se omite.")
            continue

        with zipfile.ZipFile(archivo_zip, 'r') as z:

            archivos_internos = [
                f for f in z.namelist()
                if 'pagos/' in f.lower() and 'resumen general.xlsx' in f.lower()
            ]

            if not archivos_internos:
                print("No se encontró 'resumen general.xlsx'")
                continue

            with z.open(archivos_internos[0]) as archivo_excel:

                df = pd.read_excel(
                    archivo_excel,
                    sheet_name='Transacciones + cancelaciones',
                    engine="calamine"
                )

                # Limpieza
                df = df[~df[df.columns[1]].isna()]
                df.columns = df.iloc[0].values
                df = df.iloc[1:]

                dfs.append(df)



else:
    print("⚠️ No se encontraron archivos ZIP. Buscando CSV...")
    
    archivos_csv = list(ruta_addi.glob("*.csv"))

    if archivos_csv:
        print(f"Se encontraron {len(archivos_csv)} CSV")
        dfs = rc.consolidar_carpeta(ruta_carpeta=ruta_addi, extension='csv', sep=',')
    else:
        raise FileNotFoundError("No se encontraron archivos ZIP ni CSV en la carpeta.")

⚠️ No se encontraron archivos ZIP. Buscando CSV...
Se encontraron 1 CSV
Buscando archivos con extensión '.csv' en: G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\conciliaciones_ecommerce\addi
  - Archivo 'transactions (12).csv' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [26]:
ventas_shopi[ventas_shopi['Name']=='#82344']

Empty DataFrame
Columns: [Name, Email, Financial Status, Paid at, Fulfillment Status, Fulfilled at, Accepts Marketing, Currency, Subtotal, Shipping, Taxes, Total, Discount Code, Discount Amount, Shipping Method, Created at, Lineitem quantity, Lineitem name, Lineitem price, Lineitem compare at price, Lineitem sku, Lineitem requires shipping, Lineitem taxable, Lineitem fulfillment status, Billing Name, Billing Street, Billing Address1, Billing Address2, Billing Company, Billing City, Billing Zip, Billing Province, Billing Country, Billing Phone, Shipping Name, Shipping Street, Shipping Address1, Shipping Address2, Shipping Company, Shipping City, Shipping Zip, Shipping Province, Shipping Country, Shipping Phone, Notes, Note Attributes, Cancelled at, Payment Method, Payment Reference, Refunded Amount, Vendor, Outstanding Balance, Employee, Location, Device ID, Id, Tags, Risk Level, Source, Lineitem discount, Tax 1 Name, Tax 1 Value, Tax 2 Name, Tax 2 Value, Tax 3 Name, Tax 3 Value, Tax 4 Name, Tax 4 Value, Tax 5 Name, Tax 5 Value, Phone, Receipt Number, Duties, Billing Province Name, Shipping Province Name, Payment ID, Payment Terms Name, Next Payment Due At, Payment References, NUMERO_FACTURA, REFERENCIA, Period]
Index: []

[0 rows x 82 columns]

In [27]:
ventas_shopi = ventas_shopi[ventas_shopi['Payment ID'].notna()]

In [28]:
ventas_shopi.columns

Index(['Name', 'Email', 'Financial Status', 'Paid at', 'Fulfillment Status',
       'Fulfilled at', 'Accepts Marketing', 'Currency', 'Subtotal', 'Shipping',
       'Taxes', 'Total', 'Discount Code', 'Discount Amount', 'Shipping Method',
       'Created at', 'Lineitem quantity', 'Lineitem name', 'Lineitem price',
       'Lineitem compare at price', 'Lineitem sku',
       'Lineitem requires shipping', 'Lineitem taxable',
       'Lineitem fulfillment status', 'Billing Name', 'Billing Street',
       'Billing Address1', 'Billing Address2', 'Billing Company',
       'Billing City', 'Billing Zip', 'Billing Province', 'Billing Country',
       'Billing Phone', 'Shipping Name', 'Shipping Street',
       'Shipping Address1', 'Shipping Address2', 'Shipping Company',
       'Shipping City', 'Shipping Zip', 'Shipping Province',
       'Shipping Country', 'Shipping Phone', 'Notes', 'Note Attributes',
       'Cancelled at', 'Payment Method', 'Payment Reference',
       'Refunded Amount', 'Vendor', 'Outstanding Balance', 'Employee',
       'Location', 'Device ID', 'Id', 'Tags', 'Risk Level', 'Source',
       'Lineitem discount', 'Tax 1 Name', 'Tax 1 Value', 'Tax 2 Name',
       'Tax 2 Value', 'Tax 3 Name', 'Tax 3 Value', 'Tax 4 Name', 'Tax 4 Value',
       'Tax 5 Name', 'Tax 5 Value', 'Phone', 'Receipt Number', 'Duties',
       'Billing Province Name', 'Shipping Province Name', 'Payment ID',
       'Payment Terms Name', 'Next Payment Due At', 'Payment References',
       'NUMERO_FACTURA', 'REFERENCIA', 'Period'],
      dtype='object')

In [29]:
dfs['ID Orden']

0       rsFfg3B7PEJqld9XUQsWjhLBV
1       r2gRMdBHmXwMg3s1pqnMme69s
2            DDD-1621643987825-01
3       rHnoCMLdzjOiwvi2Wyj0nr6uZ
4       rXZUvEJOeHjTusxnM95P5jpG1
                  ...
4367    r9mAUoisZQq3hkWh6NEmhnBvB
4368    r3y7VZTxRwyxTFVO8cKp7aX9j
4369    rKHMU3b5b571OpexRRh3zIji7
4370    r1CqqGAEHYgubwa7xaZPC8wrl
4371    ryaTLfAJQMDzDqDMIdFTOhWbZ
Name: ID Orden, Length: 4372, dtype: object

In [30]:

if len(archivos_zip)> 1: 
    df_concatenado = pd.concat(dfs, ignore_index=True)
    ventas_shopi['Payment Reference'] = ventas_shopi['Payment Reference'].str.strip()
    dfs['ID Orden'] = dfs['ID Orden'].str.strip()
    # 🔗 Merge con ventas Shopify
    df_concatenado = df_concatenado.merge(
        ventas_shopi[['Payment Reference', 'Total','Shipping', 'NUMERO_FACTURA']],
        left_on='Id pedido',
        right_on='Payment Reference',
        how='left'
    )
    # ✅ Validación
    df_concatenado['Validacion'] = np.where(
        df_concatenado['Total'] == df_concatenado['Total Después de\ndescuentos (2)'],
        'Conciliado',
        'No Conciliado'
    )
else:  
    ventas_shopi['Payment Reference'] = ventas_shopi['Payment Reference'].str.strip()
    dfs['ID Orden'] = dfs['ID Orden'].str.strip()

    df_concatenado = dfs.merge(
        ventas_shopi[['Payment Reference', 'Total', 'Shipping', 'NUMERO_FACTURA']],
        left_on='ID Orden',
        right_on='Payment Reference',
        how='left'
    )

    # ✅ Validación
    df_concatenado['Validacion'] = np.where(
        df_concatenado['Total'] == df_concatenado['Monto'],'Conciliado',
            np.where(df_concatenado['Estado'].isin(['Cancelada', 'Abandono','Rechazada']), 'Rechazada/Cancelada',
                     np.where(df_concatenado['Total'].isna(), 'No esta en shopify',
        'No Conciliado'))
    )

In [31]:


# 💾 Guardar resultado
df_concatenado.to_excel(
    ruta_salida / 'conciliado_addi.xlsx',
    index=False
)

print("✅ Archivo generado correctamente")

✅ Archivo generado correctamente

In [34]:
mercado_pago.columns

Index(['external_reference', 'ID DE OPERACIÓN EN MERCADO PAGO',
       'CÓDIGO DE LA CUENTA DEL VENDEDOR', 'TIPO DE MEDIO DE PAGO',
       'MEDIO DE PAGO', 'PAÍS DE ORIGEN DE LA CUENTA DE MERCADO PAGO',
       'TIPO DE OPERACIÓN', 'VALOR DE LA COMPRA', 'MONEDA',
       'MONTO RECIBIDO POR COMPRAS POR SPLIT', 'FECHA DE ORIGEN',
       'COMISIONES + IVA', 'MONTO NETO DE LA OPERACIÓN QUE IMPACTÓ TU DINERO',
       'MONEDA DE LA LIQUIDACIÓN', 'FECHA DE APROBACIÓN',
       'MONTO NETO DE LA OPERACIÓN', 'CUPÓN DE DESCUENTO', 'DATOS EXTRA',
       'COMISIÓN DE MERCADO LIBRE + IVA',
       'COMISIÓN POR OFRECER CUOTAS SIN INTERÉS', 'COSTO DE ENVÍO',
       'IMPUESTOS COBRADOS POR RETENCIONES DE IIBB', 'CUOTAS',
       'DETALLE DE IMPUESTOS', 'ID DE CAJA', 'ID DE TIENDA',
       'NOMBRE DE TIENDA', 'ID DE CAJA DEFINIDO POR EL USUARIO',
       'NOMBRE DE CAJA', 'ID DE TIENDA DEFINIDO POR EL USUARIO',
       'ID DE LA ORDEN', 'ID DEL ENVÍO', 'MODO DE ENVÍO', 'ID DEL PAQUETE',
       'IMPUESTOS DESAGREGADOS', 'NÚMERO DE SERIE DEL LECTOR (S/N)',
       'BILLETERA VIRTUAL', 'BANCO DE ORIGEN', 'NÚMERO INICIAL DE TARJETA',
       'OPERATION_TAGS', 'CANAL DE VENTA', 'PLATAFORMA DE COBRO',
       'FECHA DE LIBERACIÓN DEL DINERO', 'CÓDIGO DE PRODUCTO SKU',
       'DETALLE DE LA VENTA', 'ID DE INTENTO DE OPERACIÓN', 'FRANCHISE',
       'LAST_FOUR_DIGITS', 'ID DE LA SOLICITUD', 'PERIODO DE FACTURACIÓN',
       'NOMBRE DEL EMISOR', 'NÚMERO DE CUENTA BANCARIA DE PAGO', 'LIBERADO',
       'MONTO DE LA PROPINA', 'ID DE LA COMPRA', 'ID DE ASOCIACIÓN DE ENVÍOS',
       'MONTO TOTAL DEL CUPÓN DE DESCUENTO', 'Payment Reference', 'Total',
       'Shipping'],
      dtype='object')

In [35]:
if   df_mercado:
    mercado_pago['Validacion'] = np.where(
        mercado_pago['Total'] == mercado_pago['VALOR DE LA COMPRA'],'Conciliado',
                        np.where(mercado_pago['Total'].isna(), 'No esta en shopify',
        'No Conciliado'))
    

else:
    mercado_pago['Validacion'] = np.where(
        mercado_pago['Total'] == mercado_pago['Valor del producto (transaction_amount)'],'Conciliado',
            np.where(~mercado_pago['Estado de la operación (status)'].isin(['approved']), 'Rechazada/Cancelada',
                        np.where(mercado_pago['Total'].isna(), 'No esta en shopify',
        'No Conciliado'))
    )

mercado_pago.to_excel(ruta / 'conciliaciones_ecommerce' / 'resultados' / 'mercadopago' / 'conciliado_mercadopago.xlsx', index=False)

In [ ]:
ventas_shopi[ventas_shopi['Name']=='#82344']

Empty DataFrame
Columns: [Name, Email, Financial Status, Paid at, Fulfillment Status, Fulfilled at, Accepts Marketing, Currency, Subtotal, Shipping, Taxes, Total, Discount Code, Discount Amount, Shipping Method, Created at, Lineitem quantity, Lineitem name, Lineitem price, Lineitem compare at price, Lineitem sku, Lineitem requires shipping, Lineitem taxable, Lineitem fulfillment status, Billing Name, Billing Street, Billing Address1, Billing Address2, Billing Company, Billing City, Billing Zip, Billing Province, Billing Country, Billing Phone, Shipping Name, Shipping Street, Shipping Address1, Shipping Address2, Shipping Company, Shipping City, Shipping Zip, Shipping Province, Shipping Country, Shipping Phone, Notes, Note Attributes, Cancelled at, Payment Method, Payment Reference, Refunded Amount, Vendor, Outstanding Balance, Employee, Location, Device ID, Id, Tags, Risk Level, Source, Lineitem discount, Tax 1 Name, Tax 1 Value, Tax 2 Name, Tax 2 Value, Tax 3 Name, Tax 3 Value, Tax 4 Name, Tax 4 Value, Tax 5 Name, Tax 5 Value, Phone, Receipt Number, Duties, Billing Province Name, Shipping Province Name, Payment ID, Payment Terms Name, Next Payment Due At, Payment References, NUMERO_FACTURA, REFERENCIA, Period]
Index: []

[0 rows x 82 columns]

# PAYU

In [ ]:
mercado_pago = mercado_pago.merge(ventas_shopi[['Payment Reference','Total', 'Shipping']].dropna(), left_on='Código de referencia (external_reference)', right_on='Payment Reference', how='left')

In [ ]:
payu = rc.consolidar_carpeta(ruta_carpeta=ruta_payu, extension='csv')

Buscando archivos con extensión '.csv' en: G:\Otros ordenadores\Mi portátil\VENTA MENSUAL\conciliaciones_ecommerce\payu
  - Archivo '07.Julio.csv' leído correctamente.
  - Archivo '08.Agosto.csv' leído correctamente.
  - Archivo '09.Septiembre.csv' leído correctamente.
  - Archivo '10.Octubre.csv' leído correctamente.
  - Archivo '01.Enero.csv' leído correctamente.
  - Archivo '02.Febrero.csv' leído correctamente.
  - Archivo '03.Marzo.csv' leído correctamente.
  - Archivo '04.Abril.csv' leído correctamente.
  - Archivo '05.Mayo.csv' leído correctamente.
  - Archivo '06.Junio.csv' leído correctamente.
Concatenando todos los archivos...
¡Consolidación completada!

In [ ]:
payu.columns

Index(['Id Transacción', 'Id Orden', 'Fecha de creación',
       'Última actualización', 'Referencia', 'Descripción',
       'Nombre del pagador', 'Email del comprador', 'Valor original',
       'Moneda original', 'Valor procesado', 'Moneda procesada',
       'Estado de orden', 'Medio de pago', 'Tipo de tarjeta de crédito',
       'Número visible tarjeta de crédito', 'Banco emisor',
       'Tipo de transacción', 'Estado de transacción', 'Código de respuesta',
       'Número de cuotas totales', 'Código de trazabilidad', 'id aliado',
       'Fecha aprobación pago'],
      dtype='object')

In [ ]:
payu = payu.merge(ventas_shopi[['Payment Reference','Total', 'Shipping']].dropna(), left_on='Referencia',right_on='Payment Reference', how='left')

In [ ]:
payu['Código de respuesta'].value_counts()

Código de respuesta
APPROVED                                    20821
ANTIFRAUD_REJECTED                           1228
ABANDONED_TRANSACTION                        1194
PAYMENT_NETWORK_REJECTED                      979
ENTITY_DECLINED                               878
INVALID_TRANSACTION                           616
INSUFFICIENT_FUNDS                            334
NOT_ACCEPTED_TRANSACTION                      322
RESTRICTED_CARD                               190
INVALID_EXPIRATION_DATE_OR_SECURITY_CODE      171
INVALID_CARD                                  139
BANK_UNREACHABLE                              135
EXCEEDED_AMOUNT                               132
BANK_FRAUD_REJECTED                            84
INVALID_BANK_ACCOUNT                           56
PENDING_TRANSACTION_CONFIRMATION               50
PENDING_PAYMENT_IN_ENTITY                      44
PENDING_TRANSACTION_REVIEW                     34
EXPIRED_CARD                                   30
INTERNAL_PAYMENT_PROVIDER_ERROR                26
REPEAT_TRANSACTION                             12
ERROR                                           9
INACTIVE_PAYMENT_PROVIDER                       5
Name: count, dtype: int64

In [ ]:
payu['Validacion'] = np.where(
    payu['Total'] == payu['Valor procesado'],'Conciliado',
        np.where(~payu['Estado de transacción'].isin(['approved']), 'Rechazada/Cancelada',
                    np.where(payu['Total'].isna(), 'No esta en shopify',
    'No Conciliado'))
)

In [ ]:

payu.to_excel(ruta / 'conciliaciones_ecommerce' / 'resultados' / 'payu' / 'conciliado_payu.xlsx', index=False)